"""
Section/field metadata for rwGUI.
Python translation of constants.ts — all fixes applied:
  - No dead types (ModData removed)
  - isMulti flag explicit on every section
"""

SECTIONS_DATA = {
    "modInfoSection": {
        "id": "mod_info",
        "title": "Mod Manifest",
        "description": "Configuration for mod-info.txt used by the game browser.",
        "isMulti": False,
        "fields": [
            {"id": "title",               "label": "Mod Title",          "type": "string",  "description": "Display name of the mod.",                    "example": "My Awesome Mod"},
            {"id": "description",         "label": "Description",        "type": "string",  "description": "Brief overview of what the mod does.",         "example": "Adds new experimental units."},
            {"id": "id",                  "label": "Internal ID",        "type": "string",  "description": "Unique ID for dependency tracking.",           "example": "com.user.coolmod"},
            {"id": "tags",                "label": "Tags",               "type": "string",  "description": "Comma-separated tags (e.g. units, sample).",   "example": "units, tank"},
            {"id": "minVersion",          "label": "Min Version",        "type": "string",  "description": "Minimum game version required.",               "example": "1.15"},
            {"id": "requiredMods",        "label": "Required Mods",      "type": "string",  "description": "List of mod IDs this depends on.",             "example": "base-expansion"},
            {"id": "requiredModsMessage", "label": "Missing Dep Message","type": "string",  "description": "Message shown if dependencies are missing.",   "example": "Please install the Base Expansion mod."},
        ],
    },

    "modSections": [
        {
            "id": "core", "title": "Core Unit Functions", "isMulti": False,
            "description": "Basic unit characteristics: HP, price, mass, radius.",
            "fields": [
                {"id": "name",                "label": "Unit Name",       "type": "string",  "description": "Internal unit name for identification.",      "example": "customTank1"},
                {"id": "class",               "label": "Class",           "type": "string",  "description": "Reserved for future use.",                    "example": ""},
                {"id": "maxHp",               "label": "Max HP",          "type": "number",  "description": "Maximum health points.",                      "example": "200"},
                {"id": "startHealthAtZero",   "label": "Start HP at Zero?","type": "boolean","description": "Spawn with 0 HP (needs regen).",             "example": "false"},
                {"id": "selfRegenRate",       "label": "Self Regen Rate", "type": "float",   "description": "HP regenerated per tick.",                  "example": "0.1"},
                {"id": "maxShield",           "label": "Max Shield",      "type": "number",  "description": "Maximum shield value.",                     "example": "100"},
                {"id": "shieldRegen",         "label": "Shield Regen",    "type": "float",   "description": "Shield regeneration rate.",                 "example": "0.2"},
                {"id": "energyMax",           "label": "Max Energy",      "type": "number",  "description": "Maximum energy storage.",                   "example": "500"},
                {"id": "energyRegen",         "label": "Energy Regen",    "type": "float",   "description": "Energy regeneration rate.",                 "example": "0.5"},
                {"id": "price",               "label": "Price",           "type": "price",   "description": "Cost to build (credits, resources).",         "example": "500, gold=10"},
                {"id": "streamingCost",       "label": "Streaming Cost",  "type": "price",   "description": "Ongoing cost while alive/built.",           "example": "credits=1"},
                {"id": "mass",                "label": "Mass",            "type": "number",  "description": "Weight — affects collisions.",                "example": "3000"},
                {"id": "radius",              "label": "Selection Radius","type": "number",  "description": "Circular area for selection/collision.",       "example": "20"},
                {"id": "armour",              "label": "Armour",          "type": "float",   "description": "Damage reduction factor (1.13+).",          "example": "0.5"},
                {"id": "techLevel",           "label": "Tech Level",      "type": "enum",    "description": "Tech tier of the unit.",                      "example": "1",   "options": ["1","2","3"]},
                {"id": "buildSpeed",          "label": "Build Speed",     "type": "string",  "description": "Time to build (e.g. 3s or 0.01).",            "example": "3s"},
                {"id": "isBio",               "label": "Is Biological?",  "type": "boolean", "description": "Affects sounds and splats.",                  "example": "false"},
                {"id": "isBug",               "label": "Is Bug?",         "type": "boolean", "description": "Marks unit as insect/bug type.",              "example": "false"},
                {"id": "isBuilder",           "label": "Is Builder?",     "type": "boolean", "description": "Required for placing buildings.",             "example": "false"},
                {"id": "isBuilding",          "label": "Is Building?",    "type": "boolean", "description": "Marks unit as a static structure.",           "example": "false"},
                {"id": "generation_credits",  "label": "Gen Credits",     "type": "float",   "description": "Credits generated per tick.",                 "example": "0.5"},
                {"id": "generation_resources","label": "Gen Resources",   "type": "string",  "description": "Resources generated (resourceName=amount).",  "example": "gold=0.1"},
                {"id": "copyFrom",            "label": "Copy From",       "type": "string",  "description": "Inherit from another unit/template.",         "example": ":TEMPLATE_UNIT:"},
                {"id": "altNames",            "label": "Alt Names",       "type": "string",  "description": "Alternative names for compatibility.",        "example": "oldTankName"},
                {"id": "footprint",           "label": "Footprint",       "type": "string",  "description": "Grid space occupied (e.g. 2x2).",             "example": "2x2"},
                {"id": "showInEditor",        "label": "Show in Editor?", "type": "boolean", "description": "Display in map editor.",                      "example": "true"},
                {"id": "ignoreInUnitCapCalculation","label":"Ignore Cap?","type": "boolean", "description": "Exclude from unit cap limits.",               "example": "false"},
                {"id": "soundOnAttackOrder",  "label": "Attack Sound",    "type": "sound",   "description": "Played when ordered to attack.",              "example": "tankAttack.wav"},
                {"id": "soundOnMoveOrder",    "label": "Move Sound",      "type": "sound",   "description": "Played when ordered to move.",                "example": "tankMove.wav"},
                {"id": "soundOnNewSelection", "label": "Select Sound",    "type": "sound",   "description": "Played when unit is selected.",               "example": "tankSelect.wav"},
                {"id": "soundOnDeath",        "label": "Death Sound",     "type": "sound",   "description": "Played when unit is destroyed.",              "example": "explosion.wav"},
                {"id": "spawnUnitOnDeath",    "label": "Spawn on Death",  "type": "string",  "description": "Unit spawned when this dies.",                "example": "explosiveDrone"},
                {"id": "detectionRange",      "label": "Detection Range", "type": "number",  "description": "Vision range for detecting enemies.",           "example": "300"},
                {"id": "isTransporter",       "label": "Is Transporter?", "type": "boolean", "description": "Can carry other units.",                      "example": "true"},
                {"id": "transportSlotsCount", "label": "Transport Slots", "type": "number",  "description": "Number of units it can carry.",               "example": "4"},
                {"id": "repairRate",          "label": "Repair Rate",     "type": "float",   "description": "HP repaired per tick to others.",             "example": "0.5"},
                {"id": "nanoRepairRange",     "label": "Nano Range",      "type": "number",  "description": "Range for nano-repair ability.",              "example": "100"},
            ],
        },
        {
            "id": "graphics", "title": "Graphics & Visuals", "isMulti": False,
            "description": "Body sprites, shadows, draw layers.",
            "fields": [
                {"id": "image",            "label": "Body Image",    "type": "file",   "description": "Path to unit body sprite.",           "example": "body.png"},
                {"id": "image_wreak",      "label": "Wreck Image",   "type": "file",   "description": "Image used when unit dies.",          "example": "wreck.png"},
                {"id": "image_turret",     "label": "Turret Image",  "type": "file",   "description": "Sprite for turret (if separate).",    "example": "turret.png"},
                {"id": "image_shadow",     "label": "Shadow Image",  "type": "file",   "description": "Custom shadow sprite.",               "example": "shadow.png"},
                {"id": "total_frames",     "label": "Total Frames",  "type": "number", "description": "Number of frames for body animation.","example": "1"},
                {"id": "imageScale",       "label": "Image Scale",   "type": "float",  "description": "Multiplier for image size.",          "example": "1.0"},
                {"id": "imageRotate",      "label": "Image Rotate?", "type": "boolean","description": "Rotate image with direction.",          "example": "true"},
                {"id": "imageFlipY",       "label": "Flip Y?",       "type": "boolean","description": "Flip image vertically.",                "example": "false"},
                {"id": "drawLayer",        "label": "Draw Layer",    "type": "enum",   "description": "Rendering priority.",                 "example": "ground",    "options": ["ground","ground2","air","top","underwater"]},
                {"id": "teamColoringMode", "label": "Team Coloring", "type": "enum",   "description": "Pixel treatment for team colours.",   "example": "pureGreen", "options": ["pureGreen","hueAdd","hueShift","disabled"]},
                {"id": "glowColor",        "label": "Glow Color",    "type": "string", "description": "RGB glow effect (e.g. #FF0000).",     "example": "#FFFF00"},
                {"id": "glowSize",         "label": "Glow Size",     "type": "number", "description": "Radius of glow effect.",              "example": "5"},
                {"id": "animationOffsetX", "label": "Anim Offset X", "type": "number", "description": "Horizontal animation offset.",        "example": "0"},
                {"id": "animationOffsetY", "label": "Anim Offset Y", "type": "number", "description": "Vertical animation offset.",          "example": "0"},
                {"id": "image_completeSilhouetteToAlliedTeam", "label": "Show Silhouette to Allies?", "type": "boolean", "description": "Show silhouette to allied players.", "example": "false"},
                {"id": "image_completeSilhouetteToEnemyTeam", "label": "Show Silhouette to Enemies?", "type": "boolean", "description": "Show silhouette to enemy players.", "example": "false"},
                {"id": "filterMode",       "label": "Filter Mode",   "type": "enum",   "description": "Texture filtering type.",             "example": "linear", "options": ["point","linear"]},
                {"id": "drawUnderShadows", "label": "Draw Under Shadows?", "type": "boolean", "description": "Render below shadow layer.",    "example": "false"},
                {"id": "drawOverHead",     "label": "Draw Over Head?", "type": "boolean", "description": "Render above unit heads.",          "example": "false"},
            ],
        },
        {
            "id": "attack", "title": "Attack Permissions", "isMulti": False,
            "description": "Global characteristics for targeting enemies.",
            "fields": [
                {"id": "canAttack",                 "label": "Can Attack?",    "type": "boolean", "description": "Allow or disallow all attacks.",         "example": "true"},
                {"id": "canAttackFlyingUnits",       "label": "Attack Air?",   "type": "boolean", "description": "Target flying units.",                   "example": "true"},
                {"id": "canAttackLandUnits",         "label": "Attack Land?",  "type": "boolean", "description": "Target ground units.",                   "example": "true"},
                {"id": "canAttackUnderwaterUnits",   "label": "Attack Water?", "type": "boolean", "description": "Target underwater units.",               "example": "false"},
                {"id": "canAttackBuildings",         "label": "Attack Buildings?","type": "boolean", "description": "Target structures.",                  "example": "true"},
                {"id": "cantAttackUnits",            "label": "Cant Attack Units?","type": "boolean", "description": "Disable unit targeting.",             "example": "false"},
                {"id": "maxAttackRange",             "label": "Max Range",     "type": "number",  "description": "Maximum targeting distance.",            "example": "250"},
                {"id": "minAttackRange",             "label": "Min Range",     "type": "number",  "description": "Minimum targeting distance.",            "example": "0"},
                {"id": "shootDelay",                 "label": "Shoot Delay",   "type": "string",  "description": "Interval between shots (ticks).",        "example": "50"},
                {"id": "rotateWithTurret",           "label": "Rotate with Turret?","type": "boolean", "description": "Body rotates with turret.",         "example": "false"},
                {"id": "turretSpeed",                "label": "Turret Speed",  "type": "float",   "description": "Turret rotation speed multiplier.",      "example": "1.0"},
                {"id": "onlyTargetsUnitIfTagged",    "label": "Only Tagged?",  "type": "boolean", "description": "Only attack units with specific tag.",   "example": "false"},
                {"id": "tagsCannotBeTargetedBy",     "label": "Safe From Tags","type": "string",  "description": "Comma-separated tags that can't target this.", "example": "air,naval"},
                {"id": "onlyAttackWithMovingTurret", "label": "Moving Turret Only?", "type": "boolean", "description": "Fire only when turret is moving.", "example": "false"},
            ],
        },
        {
            "id": "movement", "title": "Movement", "isMulti": False,
            "description": "Speed, acceleration, and terrain types.",
            "fields": [
                {"id": "movementType",          "label": "Movement Type", "type": "enum",  "description": "Terrain compatibility.",         "example": "LAND", "options": ["NONE","LAND","AIR","WATER","HOVER","BUILDING","OVER_CLIFF"]},
                {"id": "moveSpeed",             "label": "Move Speed",    "type": "float", "description": "Maximum movement velocity.",     "example": "1.2"},
                {"id": "moveAccelerationSpeed", "label": "Acceleration",  "type": "float", "description": "Speed increase per frame.",      "example": "0.07"},
                {"id": "moveDecelerationSpeed", "label": "Deceleration",  "type": "float", "description": "Speed decrease per frame.",      "example": "0.05"},
                {"id": "maxTurnSpeed",          "label": "Turn Speed",    "type": "float", "description": "Top rotation speed.",            "example": "4.0"},
                {"id": "turnAcceleration",      "label": "Turn Acceleration","type": "float", "description": "Turn acceleration rate.",       "example": "0.2"},
                {"id": "targetHeight",          "label": "Target Height", "type": "number","description": "Operating altitude.",            "example": "0"},
                {"id": "moveSliding",           "label": "Move Sliding?", "type": "boolean","description": "Enable sliding movement.",       "example": "false"},
                {"id": "moveIgnoreAirBlocks",   "label": "Ignore Air Blocks?","type": "boolean","description": "Pass through air blocks.",   "example": "false"},
                {"id": "jumpSpeed",             "label": "Jump Speed",    "type": "float", "description": "Vertical jump velocity.",        "example": "0.0"},
                {"id": "gravity",               "label": "Gravity",       "type": "float", "description": "Gravitational pull.",            "example": "0.2"},
                {"id": "bounceFactor",          "label": "Bounce Factor", "type": "float", "description": "Bounciness on collision.",       "example": "0.0"},
                {"id": "moveSpeedWater",        "label": "Water Speed",   "type": "float", "description": "Speed when in water terrain.",   "example": "0.8"},
                {"id": "slowSpeed",             "label": "Slow Speed",    "type": "float", "description": "Speed when slowed/debilitated.", "example": "0.5"},
                {"id": "floating",              "label": "Is Floating?",  "type": "boolean","description": "Floats on water surface.",       "example": "false"},
                {"id": "landBased",             "label": "Land Based?",   "type": "boolean","description": "Must stay on land.",             "example": "true"},
            ],
        },
        {
            "id": "ai", "title": "AI Behavior", "isMulti": False,
            "description": "How computer-controlled teams use this unit.",
            "fields": [
                {"id": "useAsBuilder",   "label": "Use as Builder?",   "type": "boolean","description": "AI uses this to build structures.", "example": "false"},
                {"id": "useAsTransport", "label": "Use as Transport?", "type": "boolean","description": "AI uses this to move units.",       "example": "true"},
                {"id": "useAsAttacker",  "label": "Use as Attacker?",  "type": "boolean","description": "AI uses this for attacks.",         "example": "true"},
                {"id": "buildPriority",  "label": "Build Priority",    "type": "float",  "description": "Likelihood of AI building (0-1).", "example": "0.8"},
                {"id": "maxGlobal",      "label": "Max Global Limit",  "type": "number", "description": "Max amount for AI per map.",       "example": "50"},
                {"id": "attackPriority", "label": "Attack Priority",   "type": "float",  "description": "Priority for attacking (0-1).",    "example": "0.7"},
                {"id": "retreatWhenHpLessThan","label":"Retreat HP %", "type": "float",  "description": "Retreat when HP below this %.",    "example": "0.3"},
                {"id": "allowJumpingOverWater","label":"Jump Water?","type": "boolean","description": "AI allows jumping water.",          "example": "false"},
                {"id": "useAsScout",     "label": "Use as Scout?",     "type": "boolean","description": "AI uses this for scouting.",        "example": "true"},
                {"id": "attackMoveWaitTime","label":"Attack Move Wait","type": "number", "description": "Ticks to wait before attack-move.","example": "30"},
            ],
        },
    ],

    "multiSections": [
        {
            "id": "turret", "title": "Turret", "isMulti": True,
            "description": "Turrets fire projectiles with independent targeting.",
            "fields": [
                {"id": "id",              "label": "Turret ID",     "type": "string",  "description": "Unique name for this turret.",         "example": "gun1"},
                {"id": "x",               "label": "X Position",    "type": "number",  "description": "Horizontal offset from unit center.",  "example": "0"},
                {"id": "y",               "label": "Y Position",    "type": "number",  "description": "Vertical offset from unit center.",    "example": "0"},
                {"id": "projectile",      "label": "Projectile ID", "type": "string",  "description": "The projectile fired by this turret.", "example": "1"},
                {"id": "turnSpeed",       "label": "Turn Speed",    "type": "float",   "description": "Rotation speed.",                      "example": "2.0"},
                {"id": "elevation",       "label": "Elevation",     "type": "float",   "description": "Vertical angle offset.",               "example": "0.0"},
                {"id": "recoil",          "label": "Recoil",        "type": "float",   "description": "Backward kick on fire.",               "example": "2.0"},
                {"id": "chargeTime",      "label": "Charge Time",   "type": "number",  "description": "Ticks to charge before firing.",       "example": "0"},
                {"id": "canAttackBuildings","label":"Attack Buildings?","type": "boolean","description": "Can target structures.",             "example": "true"},
                {"id": "shoot_sound",     "label": "Shoot Sound",   "type": "sound",   "description": "Sound played when firing.",            "example": "cannon_fire.wav"},
                {"id": "shoot_sound_vol", "label": "Shoot Volume",  "type": "float",   "description": "Volume level (0-1).",                  "example": "0.5"},
                {"id": "canShoot",        "label": "Can Shoot?",    "type": "boolean", "description": "If false, used for visuals/build.",    "example": "true"},
                {"id": "invisible",       "label": "Is Invisible?", "type": "boolean", "description": "Hide the turret sprite.",              "example": "false"},
                {"id": "barrel_x",        "label": "Barrel X",      "type": "number",  "description": "Barrel attachment X offset.",          "example": "0"},
                {"id": "barrel_y",        "label": "Barrel Y",      "type": "number",  "description": "Barrel attachment Y offset.",          "example": "0"},
                {"id": "barrel_length",   "label": "Barrel Length", "type": "number",  "description": "Length of barrel visual.",             "example": "15"},
            ],
        },
        {
            "id": "projectile", "title": "Projectile", "isMulti": True,
            "description": "Defines damage and flight behaviour.",
            "fields": [
                {"id": "id",           "label": "Projectile ID", "type": "string", "description": "Unique identifier.",       "example": "1"},
                {"id": "directDamage", "label": "Direct Damage", "type": "number", "description": "Damage on hit.",            "example": "30"},
                {"id": "areaDamage",   "label": "Area Damage",   "type": "number", "description": "Splash damage.",           "example": "0"},
                {"id": "areaRadius",   "label": "Area Radius",   "type": "number", "description": "Splash radius.",           "example": "0"},
                {"id": "life",         "label": "Life (Ticks)",  "type": "number", "description": "Lifespan of projectile.",  "example": "200"},
                {"id": "speed",        "label": "Speed",         "type": "float",  "description": "Flight velocity.",         "example": "5.0"},
                {"id": "image",        "label": "Image",         "type": "file",   "description": "Projectile sprite.",       "example": "bullet.png"},
                {"id": "homing",       "label": "Homing?",       "type": "boolean","description": "Track target automatically.","example": "false"},
                {"id": "trajectory",   "label": "Trajectory",    "type": "enum",   "description": "Flight path type.",        "example": "straight", "options": ["straight","arc","bounce"]},
                {"id": "armorPenetration","label":"Armor Pen",  "type": "float",  "description": "Ignore armor percentage.", "example": "0.0"},
                {"id": "splitProjectile","label":"Split Count", "type": "number", "description": "Split into sub-projectiles.","example": "0"},
                {"id": "explodeOnEndOfLife","label":"Explode at End?","type": "boolean","description": "Explode when life ends.","example": "true"},
            ],
        },
        {
            "id": "action", "title": "Action", "isMulti": True,
            "description": "Dynamic abilities triggered by players.",
            "fields": [
                {"id": "id",               "label": "Action ID",       "type": "string", "description": "Unique identifier.",                              "example": "repair"},
                {"id": "text",             "label": "Button Text",     "type": "string", "description": "Label on the UI button.",                        "example": "Repair Self"},
                {"id": "description",      "label": "Tool-tip",        "type": "string", "description": "Hover description.",                             "example": "Fix internal systems."},
                {"id": "price",            "label": "Price",           "type": "price",  "description": "Cost to trigger.",                               "example": "credits=500"},
                {"id": "cooldown",         "label": "Cooldown",        "type": "number", "description": "Ticks before can use again.",                    "example": "60"},
                {"id": "consumeEnergy",    "label": "Consume Energy",  "type": "number", "description": "Energy cost to activate.",                       "example": "100"},
                {"id": "healAmount",       "label": "Heal Amount",     "type": "number", "description": "HP restored on use.",                            "example": "50"},
                {"id": "teleport",         "label": "Teleport?",       "type": "boolean","description": "Teleport unit on activation.",                   "example": "false"},
                {"id": "playSoundAtUnit",  "label": "Unit Sound",      "type": "sound",  "description": "Sound played at the unit when action is used.",  "example": "repair.wav"},
                {"id": "playSoundGlobally","label": "Global Sound",    "type": "sound",  "description": "Sound played to everyone.",                      "example": "alert.wav"},
                {"id": "autoTrigger",      "label": "Auto Trigger",    "type": "logic",  "description": "LogicBoolean for auto-activation.",              "example": "if self.hp() < 100"},
                {"id": "convertTo",        "label": "Convert To",      "type": "string", "description": "Transform unit into another type.",              "example": "upgradedTank"},
                {"id": "spawnUnit",        "label": "Spawn Unit",      "type": "string", "description": "Create a new unit on action.",                   "example": "drone"},
                {"id": "requireCondition", "label": "Require Condition","type": "logic", "description": "Must be true to show action.",                  "example": "if self.energy() > 50"},
            ],
        },
        {
            "id": "animation", "title": "Animation", "isMulti": True,
            "description": "Frame-by-frame movement for body, turrets, and legs.",
            "fields": [
                {"id": "id",        "label": "Animation ID",    "type": "string",  "description": "Name of the animation.",                             "example": "idle"},
                {"id": "onActions", "label": "Trigger On",      "type": "string",  "description": "When this plays (idle, move, attack, etc.).",        "example": "move, idle"},
                {"id": "blendIn",   "label": "Blend In (s)",    "type": "float",   "description": "Transition-in time.",                                "example": "0.1"},
                {"id": "blendOut",  "label": "Blend Out (s)",   "type": "float",   "description": "Transition-out time.",                               "example": "0.1"},
                {"id": "pingPong",  "label": "Ping-Pong?",      "type": "boolean", "description": "Reverse at end of loop.",                            "example": "true"},
                {"id": "Keyframes", "label": "Keyframes (Raw)", "type": "logic",   "description": "Time-based frame data (body_0s: {frame:0}).",        "example": "body_0s: {frame:0}\nbody_0.5s: {frame:4}"},
            ],
        },
        {
            "id": "canBuild", "title": "Build Menu", "isMulti": True,
            "description": "Units that this unit can build.",
            "fields": [
                {"id": "name",      "label": "Unit ID",      "type": "string",  "description": "Unit identifier to build.",       "example": "heavyTank"},
                {"id": "pos",       "label": "UI Position",  "type": "float",   "description": "Order in build menu.",            "example": "1.0"},
                {"id": "tech",      "label": "Tech Tier",    "type": "number",  "description": "Required tech level.",            "example": "1"},
                {"id": "forceNano", "label": "Force Nano?",  "type": "boolean", "description": "Build as if structure.",          "example": "false"},
                {"id": "isVisible", "label": "Is Visible?",  "type": "logic",   "description": "Condition to show button.",       "example": "if self.hp() > 50"},
                {"id": "isLocked",  "label": "Is Locked?",   "type": "logic",   "description": "Condition to disable button.",    "example": "if not self.energy() > 10"},
            ],
        },
        {
            "id": "leg", "title": "Leg / Arm", "isMulti": True,
            "description": "Moveable cosmetics for mechs, infantry, etc.",
            "fields": [
                {"id": "x",           "label": "X Foot Pos",   "type": "float", "description": "Foot position horizontal.",      "example": "10"},
                {"id": "y",           "label": "Y Foot Pos",   "type": "float", "description": "Foot position vertical.",        "example": "10"},
                {"id": "attach_x",    "label": "Attach X",     "type": "float", "description": "Joint point horizontal.",        "example": "5"},
                {"id": "attach_y",    "label": "Attach Y",     "type": "float", "description": "Joint point vertical.",          "example": "5"},
                {"id": "rotateSpeed", "label": "Rotate Speed", "type": "float", "description": "Leg rotation velocity.",         "example": "2.0"},
                {"id": "heightSpeed", "label": "Height Speed", "type": "float", "description": "Vertical movement velocity.",    "example": "1.0"},
                {"id": "moveSpeed",   "label": "Move Speed",   "type": "float", "description": "Walking speed.",                 "example": "2.5"},
                {"id": "image_leg",   "label": "Leg Image",    "type": "file",  "description": "Leg sprite asset.",              "example": "leg.png"},
                {"id": "image_foot",  "label": "Foot Image",   "type": "file",  "description": "Foot sprite asset.",             "example": "foot.png"},
            ],
        },
        {
            "id": "attachment", "title": "Attachment", "isMulti": True,
            "description": "Units stacked onto this one to create compound units.",
            "fields": [
                {"id": "id",                          "label": "Slot ID",        "type": "string",  "description": "Name of attachment slot.",          "example": "cannon_mount"},
                {"id": "x",                           "label": "X Position",     "type": "float",   "description": "Horizontal offset.",                "example": "0"},
                {"id": "y",                           "label": "Y Position",     "type": "float",   "description": "Vertical offset.",                  "example": "10"},
                {"id": "height",                      "label": "Height",         "type": "float",   "description": "Elevation offset.",                 "example": "5"},
                {"id": "idleDir",                     "label": "Idle Dir",       "type": "number",  "description": "Facing direction (degrees).",       "example": "0"},
                {"id": "isVisible",                   "label": "Is Visible?",    "type": "boolean", "description": "Show the attachment.",              "example": "true"},
                {"id": "canAttack",                   "label": "Can Attack?",    "type": "boolean", "description": "Attachment can fire.",              "example": "true"},
                {"id": "onCreateSpawnUnitOf",          "label": "Unit Type",      "type": "string",  "description": "Unit to spawn in slot.",            "example": "smallTurret"},
                {"id": "prioritizeParentsMainTarget", "label": "Share Target?",  "type": "boolean", "description": "Target parent's enemy.",            "example": "true"},
            ],
        },
        {
            "id": "effect", "title": "Effect", "isMulti": True,
            "description": "Visual effects spawned by the unit.",
            "fields": [
                {"id": "id",            "label": "Effect ID",   "type": "string", "description": "Unique name.",              "example": "smoke"},
                {"id": "life",          "label": "Lifespan",    "type": "float",  "description": "Time till removal (ticks).","example": "100"},
                {"id": "image",         "label": "Image",       "type": "file",   "description": "Sprite asset.",             "example": "puff.png"},
                {"id": "scaleTo",       "label": "Scale To",    "type": "float",  "description": "End scale.",                "example": "2.0"},
                {"id": "scaleFrom",     "label": "Scale From",  "type": "float",  "description": "Start scale.",              "example": "1.0"},
                {"id": "color",         "label": "Tint Color",  "type": "string", "description": "Hex colour code.",          "example": "#FFFFFF"},
                {"id": "fadeInTime",    "label": "Fade In (s)", "type": "float",  "description": "Alpha transition time.",    "example": "0.2"},
                {"id": "xSpeedRelative","label": "Speed X",     "type": "float",  "description": "Horizontal drift.",         "example": "0.5"},
                {"id": "ySpeedRelative","label": "Speed Y",     "type": "float",  "description": "Vertical drift.",           "example": "0.5"},
            ],
        },
        {
            "id": "placementRule", "title": "Placement Rule", "isMulti": True,
            "description": "Rules for where buildings can be placed.",
            "fields": [
                {"id": "id",                  "label": "Rule ID",       "type": "string", "description": "Unique name.",                   "example": "nearFactory"},
                {"id": "searchTags",          "label": "Search Tags",   "type": "string", "description": "Find units with these tags.",    "example": "factory"},
                {"id": "searchTeam",          "label": "Search Team",   "type": "enum",   "description": "Who to look for.",               "example": "own", "options": ["own","neutral","ally","enemy","any"]},
                {"id": "searchDistance",      "label": "Distance",      "type": "number", "description": "Radius to check.",               "example": "500"},
                {"id": "minCount",            "label": "Min Units",     "type": "number", "description": "Required minimum.",              "example": "1"},
                {"id": "maxCount",            "label": "Max Units",     "type": "number", "description": "Required maximum.",              "example": "10"},
                {"id": "cannotPlaceMessage",  "label": "Error Message", "type": "string", "description": "Shown if placement failed.",     "example": "Requires a factory nearby."},
            ],
        },
        {
            "id": "resource", "title": "Local Resource", "isMulti": True,
            "description": "Local resource used by units (e.g. ammo, fuel).",
            "fields": [
                {"id": "id",               "label": "Resource ID",   "type": "string",  "description": "Internal name.",       "example": "ammo"},
                {"id": "displayName",      "label": "Display Name",  "type": "string",  "description": "Visible name.",        "example": "Missiles"},
                {"id": "displayNameShort", "label": "Short Name",    "type": "string",  "description": "Compact label.",       "example": "Msl"},
                {"id": "hidden",           "label": "Is Hidden?",    "type": "boolean", "description": "Hide from player UI.", "example": "false"},
            ],
        },
        {
            "id": "decal", "title": "Decal", "isMulti": True,
            "description": "Graphics layered onto the unit body.",
            "fields": [
                {"id": "image",           "label": "Decal Image", "type": "file",   "description": "Sprite asset.",              "example": "logo.png"},
                {"id": "layer",           "label": "Layer",       "type": "enum",   "description": "Stacking priority.",          "example": "onTop", "options": ["shadow","beforeBody","afterBody","onTop","beforeUI"]},
                {"id": "order",           "label": "Sort Order",  "type": "float",  "description": "Sub-layer priority.",         "example": "1.0"},
                {"id": "xOffsetRelative", "label": "X Offset",    "type": "float",  "description": "Horizontal shift.",           "example": "0"},
                {"id": "yOffsetRelative", "label": "Y Offset",    "type": "float",  "description": "Vertical shift.",             "example": "0"},
                {"id": "isVisible",       "label": "Is Visible?", "type": "logic",  "description": "Condition to draw.",          "example": "if self.hp() > 0"},
            ],
        },
    ],
}
